# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit ShrinkageTrees.Rmd to modify this file

## ----pkg-setup, include=FALSE-------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(ShrinkageTrees)


## ----ExampleTree, echo=FALSE, fig.cap="Schematic of a single regression tree. Interior nodes contain binary splitting rules of the form $x_\\rho < c$; terminal nodes (leaves) contain step heights $h_\\ell$. An observation traverses the tree from root to leaf, and its prediction is the step height of the leaf it reaches.", out.width="85%", fig.align='center'----
knitr::include_graphics("figures/ExampleTree_standalone.pdf")


## ----pkg-comparison, echo=FALSE-----------------------------------------------
df <- data.frame(
  Package             = c("BART", "dbarts", "bcf", "stochtree", "SoftBart", "ShrinkageTrees"),
  `Survival`          = c("Yes", "No", "No", "No", "No", "Yes"),
  `Interval\nCensoring` = c("No", "No", "No", "No", "No", "Yes"),
  `Causal\n(BCF)`     = c("No", "No", "Yes", "Yes", "No", "Yes"),
  `Dirichlet\n(DART)` = c("Yes", "No", "No", "No", "No", "Yes"),
  check.names         = FALSE
)
knitr::kable(df,
             caption = "Comparison of Bayesian tree ensemble packages in R.",
             booktabs = TRUE,
             format = "latex") |>
  kableExtra::kable_styling(
    latex_options = c("hold_position"),
    font_size = 9
  ) |>
  kableExtra::column_spec(1, width = "2.5cm") |>
  kableExtra::column_spec(2:5, width = "1.6cm")


## ----fitting-functions, echo=FALSE--------------------------------------------
df <- data.frame(
  Function = c("\\texttt{ShrinkageTrees()}", "\\texttt{HorseTrees()}",
               "\\texttt{CausalShrinkageForest()}", "\\texttt{CausalHorseForest()}",
               "",
               "\\texttt{SurvivalBART()}", "\\texttt{SurvivalDART()}",
               "\\texttt{SurvivalBCF()}", "\\texttt{SurvivalShrinkageBCF()}"),
  Description = c(
    "Prediction model with user-specified leaf prior (horseshoe, half-Cauchy, standard, Dirichlet)",
    "Prediction model with horseshoe prior; single tuning parameter $k$",
    "BCF causal model with user-specified leaf priors for $\\mu$ and $\\tau$ forests",
    "BCF causal model with horseshoe prior on both forests",
    "",
    "AFT survival with conjugate normal leaf prior (standard BART)",
    "AFT survival with Dirichlet splitting prior (DART)",
    "AFT survival with BCF decomposition and conjugate normal leaf prior",
    "AFT survival with BCF decomposition and horseshoe leaf prior"),
  check.names = FALSE
)
knitr::kable(df,
             caption = "Fitting functions in \\pkg{ShrinkageTrees}. The first four
                        are primary functions; the last four are convenience wrappers.",
             booktabs = TRUE,
             format = "latex",
             escape = FALSE) |>
  kableExtra::kable_styling(latex_options = "hold_position") |>
  kableExtra::column_spec(1, width = "4.5cm") |>
  kableExtra::column_spec(2, width = "9.5cm") |>
  kableExtra::row_spec(4, hline_after = TRUE)


## ----data, echo=TRUE, eval=FALSE----------------------------------------------
# library(ShrinkageTrees)
# data("ovarian")
# 
# clin      <- ovarian$clinical
# time      <- clin$OS_time
# status    <- clin$OS_event
# treatment <- clin$treatment
# 
# X <- cbind(age        = clin$age,
#            figo_stage = clin$figo_stage,
#            tumor_grade = clin$tumor_grade,
#            ovarian$X)
# 
# cat("n =", nrow(clin), "| p =", ncol(X),
#     "| event rate =", round(mean(status), 2),
#     "| carboplatin =", sum(treatment), "/ cisplatin =", sum(1 - treatment), "\n")


## ----split, echo=TRUE, eval=FALSE---------------------------------------------
# set.seed(2025)
# train_idx <- sample(seq_len(nrow(clin)), size = floor(0.8 * nrow(clin)))
# test_idx  <- setdiff(seq_len(nrow(clin)), train_idx)
# 
# X_train <- X[train_idx, ];  X_test <- X[test_idx, ]
# time_train <- time[train_idx];  time_test <- time[test_idx]
# status_train <- status[train_idx];  status_test <- status[test_idx]


## ----survival-horse, echo=TRUE, eval=FALSE------------------------------------
# fit_horse <- HorseTrees(
#   y               = time_train,
#   status          = status_train,
#   X_train         = X_train,
#   X_test          = X_test,
#   outcome_type    = "right-censored",
#   timescale       = "time",
#   number_of_trees = 50,
#   k               = 0.1,
#   N_post          = 5000,
#   N_burn          = 5000,
#   n_chains        = 2,
#   store_posterior_sample = TRUE,
#   verbose         = FALSE
# )


## ----survival-summary, echo=TRUE, eval=FALSE----------------------------------
# print(fit_horse)


## ----survival-summary2, echo=TRUE, eval=FALSE---------------------------------
# summary(fit_horse)


## ----cindex, echo=TRUE, eval=FALSE--------------------------------------------
# library(survival)
# c_horse <- concordance(Surv(time_test, status_test) ~ fit_horse$test_predictions)
# cat("Test C-index — HorseTrees:", round(c_horse$concordance, 3), "\n")


## ----convergence, echo=TRUE, eval=FALSE---------------------------------------
# plot(fit_horse, type = "trace")
# plot(fit_horse, type = "density")


## ----trace-fig, echo=FALSE, fig.cap="Traceplot of the posterior draws of $\\sigma$ for the Horseshoe Forest model. The two chains are shown in different colours.", out.width="85%", fig.align='center'----
knitr::include_graphics("figures/trace_horse.pdf")


## ----density-fig, echo=FALSE, fig.cap="Posterior density of $\\sigma$ for the Horseshoe Forest model, estimated separately for each chain.", out.width="85%", fig.align='center'----
knitr::include_graphics("figures/density_horse.pdf")


## ----patient-profiles, echo=TRUE, eval=FALSE----------------------------------
# pred <- predict(fit_horse, newdata = X_test)
# 
# idx_best  <- which.max(pred$mean)
# idx_worst <- which.min(pred$mean)
# 
# cat("Best prognosis  — age:", X_test[idx_best, "age"],
#     " stage:", X_test[idx_best, "figo_stage"],
#     " grade:", X_test[idx_best, "tumor_grade"], "\n")
# cat("Worst prognosis — age:", X_test[idx_worst, "age"],
#     " stage:", X_test[idx_worst, "figo_stage"],
#     " grade:", X_test[idx_worst, "tumor_grade"], "\n")


## ----individual-survival, echo=TRUE, eval=FALSE-------------------------------
# plot(pred, type = "survival", obs = c(idx_best, idx_worst))


## ----individual-fig, echo=FALSE, fig.cap="Posterior survival curves for two test-set patients at opposite ends of the predicted risk spectrum, with pointwise 95\\% credible bands.", out.width="85%", fig.align='center'----
knitr::include_graphics("figures/survival_individual.pdf")


## ----population-survival, echo=TRUE, eval=FALSE-------------------------------
# plot(fit_horse, type = "survival", km = TRUE)


## ----population-fig, echo=FALSE, fig.cap="Population-averaged posterior survival curve (solid line) with 95\\% credible band (shaded) and Kaplan--Meier estimate (dashed).", out.width="85%", fig.align='center'----
knitr::include_graphics("figures/survival_population.pdf")


## ----propensity, echo=TRUE, eval=FALSE----------------------------------------
# ps_model   <- glm(treatment ~ age + factor(figo_stage) + factor(tumor_grade),
#                    family = binomial, data = clin)
# propensity <- predict(ps_model, type = "response")
# X_control  <- cbind(propensity = propensity, X)


## ----causal-fit, echo=TRUE, eval=FALSE----------------------------------------
# set.seed(2025)
# fit_causal <- CausalHorseForest(
#   y                         = log(time),
#   status                    = status,
#   X_train_control           = X_control,
#   X_train_treat             = X,
#   treatment_indicator_train = treatment,
#   outcome_type              = "right-censored",
#   timescale                 = "log",
#   number_of_trees           = 50,
#   k                         = 0.1,
#   N_post                    = 5000,
#   N_burn                    = 5000,
#   n_chains                  = 2,
#   store_posterior_sample    = TRUE,
#   verbose                   = FALSE
# )
# summary(fit_causal)


## ----treatment-effects, echo=TRUE, eval=FALSE---------------------------------
# plot(fit_causal, type = "ate")
# plot(fit_causal, type = "cate")


## ----treatment-effects-fig, echo=FALSE, fig.cap="Left: posterior density of the average treatment effect (ATE) of carboplatin versus cisplatin on the log-survival scale, with 95\\% credible interval (dashed lines). Right: patient-level conditional average treatment effects (CATEs) sorted by posterior mean with 95\\% credible intervals; the dashed line marks zero (no effect).", out.width="48%", fig.show='hold', fig.align='center'----
knitr::include_graphics(c("figures/ate_posterior.pdf", "figures/cate_caterpillar.pdf"))

